source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "minima", "~> 2.5"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo", "~> 1.2"
gem "tzinfo-data"

# Windows specific gems
# gem "wdm", "~> 0.1.1", :platforms => [:mswin, :mingw, :x64_mingw]